python-targets:
    - 3
doc-warnings: yes
test-warnings: no
strictness: veryhigh
max-line-length: 120
ignore-paths:
    - bin
    - books
    - docs
    - engines
    - include
    - lib
    - src
    - tablebases
    - logs
    - dgt
